import Aura from '@primevue/themes/aura';

export default defineNuxtConfig({
    css: [
        '~/assets/css/global.css'
    ],

    modules: [
        '@primevue/nuxt-module',
        '@nuxtjs/tailwindcss',
        '@pinia/nuxt',
        '@nuxtjs/i18n',
        '@nuxt/icon',
    ],
    icon: {
        collections: ['uil'],
    },
    app: {
        head: {
            htmlAttrs: {
                lang: 'fa',
                dir: 'rtl',
            },
        },
    },
    runtimeConfig: {
        public: {
            mapIrApiKey: process.env.MAP_IR_API_KEY,
            apiBaseUrlAcc: process.env.API_BASE_URL_ACC,
            apiBaseUrlServ: process.env.API_BASE_URL_SERV
        }
    },
    i18n: {
        locales: [
            { code: 'fa', iso: 'fa-IR', dir: 'rtl', name: 'فارسی' },
            { code: 'en', iso: 'en-US', dir: 'ltr', name: 'English' }
        ],
        defaultLocale: 'fa',
        strategy: 'no_prefix',
        detectBrowserLanguage: false,
        vueI18n: './i18n.config.ts',
    },
    primevue: {
        options: {
            ripple: true,
            inputVariant: 'filled',
            theme: {
                preset: Aura,
                options: {
                    prefix: 'p',
                    darkModeSelector: false,
                    cssLayer: false,
                }
            },
            locale: {
                startsWith: "شروع با",
                contains: "شامل",
                notContains: "شامل نمی‌شود",
                endsWith: "پایان با",
                equals: "مساوی",
                notEquals: "مساوی نیست",
                noFilter: "بدون فیلتر",
                lt: "کمتر از",
                lte: "کمتر از یا مساوی",
                gt: "بیشتر از",
                gte: "بیشتر از یا مساوی",
                dateIs: "تاریخ است",
                dateIsNot: "تاریخ نیست",
                dateBefore: "تاریخ قبل از",
                dateAfter: "تاریخ بعد از",
                clear: "پاک کردن",
                apply: "اعمال",
                matchAll: "تمام موارد",
                matchAny: "هر موردی",
                addRule: "افزودن قاعده",
                removeRule: "حذف قاعده",
                accept: "بله",
                reject: "نه",
                choose: "انتخاب کنید",
                upload: "بارگذاری",
                cancel: "لغو",
                completed: "اتمام شده",
                pending: "در حال انجام",
                fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
                dayNames: ['یکشنبه', 'دوشنبه', 'سه‌شنبه', 'چهارشنبه', 'پنج‌شنبه', 'جمعه', 'شنبه'],
                dayNamesShort: ['یک', 'دو', 'سه', 'چهار', 'پنج', 'جمعه', 'شنبه'],
                dayNamesMin: ['ی', 'د', 'س', 'چ', 'پ', 'ج', 'ش'],
                monthNames: ['ژانویه', 'فوریه', 'مارس', 'آوریل', 'می', 'ژوئن', 'جولای', 'اوت', 'سپتامبر', 'اکتبر', 'نوامبر', 'دسامبر'],
                monthNamesShort: ['ژان', 'فور', 'مار', 'آور', 'می', 'ژو', 'جول', 'اوت', 'سپت', 'اکت', 'نوام', 'دسام'],
                chooseYear: "انتخاب سال",
                chooseMonth: "انتخاب ماه",
                chooseDate: "انتخاب تاریخ",
                prevDecade: "دهه قبل",
                nextDecade: "دهه بعد",
                prevYear: "سال قبل",
                nextYear: "سال بعد",
                prevMonth: "ماه قبل",
                nextMonth: "ماه بعد",
                prevHour: "ساعت قبل",
                nextHour: "ساعت بعد",
                prevMinute: "دقیقه قبل",
                nextMinute: "دقیقه بعد",
                prevSecond: "ثانیه قبل",
                nextSecond: "ثانیه بعد",
                am: "قبل از ظهر",
                pm: "بعد از ظهر",
                today: "امروز",
                weekHeader: "هفته",
                firstDayOfWeek: 0,
                showMonthAfterYear: false,
                dateFormat: "yy/mm/dd",
                weak: "ضعیف",
                medium: "متوسط",
                strong: "قوی",
                passwordPrompt: "یک رمز عبور وارد کنید",
                searchMessage: "{0} نتیجه موجود است",
                selectionMessage: "{0} آیتم انتخاب شده",
                emptySelectionMessage: "هیچ آیتمی انتخاب نشده",
                emptySearchMessage: "نتیجه‌ای یافت نشد",
                fileChosenMessage: "{0} فایل",
                noFileChosenMessage: "هیچ فایلی انتخاب نشده",
                emptyMessage: "هیچ گزینه‌ای موجود نیست",
                aria: {
                    trueLabel: "صحیح",
                    falseLabel: "غلط",
                    nullLabel: "انتخاب نشده",
                    star: "1 ستاره",
                    stars: "{star} ستاره",
                    selectAll: "تمام آیتم‌ها انتخاب شده",
                    unselectAll: "تمام آیتم‌ها از انتخاب خارج شده",
                    close: "بستن",
                    previous: "قبلی",
                    next: "بعدی",
                    navigation: "ناوبری",
                    scrollTop: "اسکرول بالا",
                    moveTop: "حرکت به بالا",
                    moveUp: "حرکت به بالا",
                    moveDown: "حرکت به پایین",
                    moveBottom: "حرکت به پایین‌ترین",
                    moveToTarget: "انتقال به مقصد",
                    moveToSource: "انتقال به مبدا",
                    moveAllToTarget: "انتقال همه به مقصد",
                    moveAllToSource: "انتقال همه به مبدا",
                    pageLabel: "صفحه {page}",
                    firstPageLabel: "صفحه اول",
                    lastPageLabel: "آخرین صفحه",
                    nextPageLabel: "صفحه بعدی",
                    prevPageLabel: "صفحه قبلی",
                    rowsPerPageLabel: "ردیف‌ها در هر صفحه",
                    jumpToPageDropdownLabel: "پرش به صفحه از منو",
                    jumpToPageInputLabel: "پرش به صفحه از ورودی",
                    selectRow: "ردیف انتخاب شده",
                    unselectRow: "ردیف انتخاب نشده",
                    expandRow: "گسترش ردیف",
                    collapseRow: "بستن ردیف",
                    showFilterMenu: "نمایش منوی فیلتر",
                    hideFilterMenu: "مخفی کردن منوی فیلتر",
                    filterOperator: "عملگر فیلتر",
                    filterConstraint: "محدودیت فیلتر",
                    editRow: "ویرایش ردیف",
                    saveEdit: "ذخیره ویرایش",
                    cancelEdit: "لغو ویرایش",
                    listView: "نمایش لیست",
                    gridView: "نمایش شبکه",
                    slide: "اسلاید",
                    slideNumber: "اسلاید {slideNumber}",
                    zoomImage: "زوم تصویر",
                    zoomIn: "زوم به داخل",
                    zoomOut: "زوم به خارج",
                    rotateRight: "چرخاندن به راست",
                    rotateLeft: "چرخاندن به چپ"
                }
            }
        }
    },

    compatibilityDate: '2025-02-06'
})